# Generated by Django 5.1 on 2024-01-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='raw_time',
            field=models.FloatField(default=9.5),
            preserve_default=False,
        ),
    ]
