# Generated by Django 5.1 on 2024-01-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_app', '0002_path_raw_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='popularity_coeff',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
