# Generated by Django 5.0.1 on 2024-01-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_app', '0003_path_popularity_coeff'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='current_time',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
