# Generated by Django 5.0.1 on 2024-01-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_app', '0004_path_current_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='weather',
            field=models.CharField(choices=[('sun', 'Sun'), ('rain', 'Rain'), ('snow', 'Snow'), ('fog', 'Fog')], default='sun', max_length=10, null=True),
        ),
    ]
